language: c
sudo: required

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get install gfortran
    - osx: osx
      before_install:
        - conda install gcc

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - ls