language: c
sudo: required

compiler:
  - gcc
  - clang

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get install gfortran
    - os: linux
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install mpich2
    - os: linux
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install openmpi-bin
    - os: osx
      before_install:
        - brew install gcc > /dev/null
        - export FC=gfortran

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - ls