language: c
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install mpich2
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
    - os: osx
      compiler: gcc
      before_install:
        - brew install gcc > /dev/null
        - export FC=gfortran
    - os: windows
      compiler: gcc
      env:
         - CMAKE="-G "MinGW Makefiles" -Dlanguage=Python"
         - MAKE="mingw32-make"
      before_install:
           # remove the sh.exe file, which prevents MinGW from working
         - where sh > sh_loc.txt
         - powershell -command "cat sh_loc.txt | rm"
      install:
         - mkdir build
         - cd build
         - cmake env(CMAKE) ../
         - env(MAKE)
#         - cmake -G "MinGW Makefiles" -Dlanguage=Python ../
#         - mingw32-make

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - ls