language: c
sudo: required

os:
  - linux
  - osx
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install gfortran

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - ls