language: c
sudo: required

matrix:
  include:
#    - os: linux
#      compiler: gcc
#      before_install:
#        - sudo apt-get install gfortran
#    - os: linux
#      compiler: gcc
#      before_install:
#        - sudo apt-get install gfortran
#        - sudo apt-get install mpich2
#    - os: linux
#      compiler: gcc
#      before_install:
#        - sudo apt-get install gfortran
#        - sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev
#    - os: osx
#      compiler: gcc
#      before_install:
#        - brew install gcc > /dev/null
#        - export FC=gfortran
    - os: windows
      compiler: gcc
      env:
         - CMAKE="-Dlanguage=Python"
      before_install:
         - dir
      install:
         - ls
         - where sh
         - rm "C:/Program Files/Git/usr/bin/sh.exe"
#         - powershell -command "where sh | rm"
#         - where sh
         - echo $PATH
         - echo $MAKEFLAGS
#         - setx MAKEFLAGS "SHELL=cmd"
         - set MAKEFLAGS=SHELL=cmd
         - echo $MAKEFLAGS
         - mkdir build
         - cd build
#         - cmake -G "Visual Studio 15 2017" -Dlanguage=Python ../
         - cmake -G "MinGW Makefiles" -Dlanguage=Python ../
#         - cmake -Dlanguage=Python ../
         - dir
#         - vcvarsall.bat amd64_arm uwp -vcvars_ver=14.10
#         - vcvars32.bat
#         - nmake
         - mingw32-make
#         - 
#         - powershell -command "(new-object System.Net.WebClient).DownloadFile('https://cygwin.com/setup-x86_64.exe','setup-x86_64.exe')"
#         - dir
#         - ./setup-x86_64.exe
#        - cd
#        - mkdir testdir
#        - echo echo Hello World > ./testdir/test.ps1
#        - dir
#        - type ./testdir/test.ps1
#        - powershell \test.ps1
#        - echo (new-object System.Net.WebClient).DownloadFile('https://cygwin.com/setup-x86_64.exe','C:\setup-x86_64.exe') > cygwin_download.ps1
#        - powershell cygwin_download.ps1
#        - C:\setup-x86_64.exe

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - ls