language: c
sudo: required

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get install gfortran
      compiler: gcc
    - osx: osx
      before_install:
        - conda install gcc
      compiler: gcc

install:
  - mkdir build
  - cd build
  - cmake ../
  - make

script:
  - ls